package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        maven {
            goals = "war:war"
        }
    }
    steps {
        insert(1) {
            step {
                name = "Deploy"
                type = "ssh-deploy-runner"
                param("jetbrains.buildServer.deployer.username", "root")
                param("teamcitySshKey", "id_rsa")
                param("jetbrains.buildServer.deployer.sourcePath", "/opt")
                param("jetbrains.buildServer.deployer.targetUrl", "192.168.0.112")
                param("jetbrains.buildServer.sshexec.authMethod", "UPLOADED_KEY")
                param("jetbrains.buildServer.deployer.ssh.transport", "jetbrains.buildServer.deployer.ssh.transport.scp")
            }
        }
    }
}
